image: themattrix/tox

stages:
  - test
  - release

static_check:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y git
    - pip3.6 install -r requirements_dev.txt

  script:
    - $(find /.pyenv/versions -name pre-commit) run -a --hook-stage=manual

tests:
  stage: test
  script:
  - tox


docs:
  before_script:
    - pip3.6 install --upgrade pip
    - pip3.6 install -r requirements_dev.txt

  script:
  - pip3.6 install .
  - cd docs/
  - $(find /.pyenv/versions -name sphinx-build) -b html -d build/doctrees -W source build/html


pypi:
  image: python:3.8
  variables:
    TWINE_USERNAME: "__token__"
  stage: release
  needs: [tests, static_check]
  rules:
  - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
    when: on_success
  script:
      - pip install -U twine gitchangelog pystache
      - echo "" >> README.md
      - gitchangelog >> README.md
      - python setup.py sdist bdist_wheel
      - twine upload --verbose dist/*
